In [1]:
import time

import numpy as np

In [2]:
def reduce(aa):
    return np.abs(aa) % 10

In [3]:
inp_ex = [int(aa) for aa in list('12345678')]
# inp_ex = [9, 8, 7, 6, 5]

In [4]:
ex_pattern = [0, 1, 0, -1]

In [5]:
def get_matrix(ex_pattern, N):
    mat = np.ones((N, N))*-99
    for ii in range(N):
        for jj in range(N):
            mat[ii, jj] = ex_pattern[((jj+1)//(ii+1)) % len(ex_pattern)]
    return mat

In [6]:
mat = get_matrix(ex_pattern, 8)
print(mat)

[[ 1.  0. -1.  0.  1.  0. -1.  0.]
 [ 0.  1.  1.  0.  0. -1. -1.  0.]
 [ 0.  0.  1.  1.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.]]


In [7]:
def next_phase(inp_ll, mat):
    return reduce([aa for aa in np.matmul(mat, inp_ll)])

In [8]:
inp_ex = [int(aa) for aa in list('59776034095811644545367793179989602140948714406234694972894485066523525742503986771912019032922788494900655855458086979764617375580802558963587025784918882219610831940992399201782385674223284411499237619800193879768668210162176394607502218602633153772062973149533650562554942574593878073238232563649673858167635378695190356159796342204759393156294658366279922734213385144895116649768185966866202413314939692174223210484933678866478944104978890019728562001417746656699281992028356004888860103805472866615243544781377748654471750560830099048747570925902575765054898899512303917159138097375338444610809891667094051108359134017128028174230720398965960712')]
mat = get_matrix(ex_pattern, len(inp_ex))
cur = inp_ex
for _ in range(100):
    cur = next_phase(cur, mat)
print(cur[:8])

[8. 9. 5. 7. 6. 8. 2. 8.]


In [9]:
# Part one solution
''.join([str(int(cc)) for cc in cur[:8]])

'89576828'

In [10]:
# Repeat puzzle input 10000 times
# 

In [11]:
# For late points, it's simply a matter of summing the appropriate points

In [12]:
inp_str = '59776034095811644545367793179989602140948714406234694972894485066523525742503986771912019032922788494900655855458086979764617375580802558963587025784918882219610831940992399201782385674223284411499237619800193879768668210162176394607502218602633153772062973149533650562554942574593878073238232563649673858167635378695190356159796342204759393156294658366279922734213385144895116649768185966866202413314939692174223210484933678866478944104978890019728562001417746656699281992028356004888860103805472866615243544781377748654471750560830099048747570925902575765054898899512303917159138097375338444610809891667094051108359134017128028174230720398965960712'
len_inp = len(inp_str)
len_all = len_inp * 10000

inp_ex = [int(aa) for aa in list(inp_str)]
offset = int(inp_str[:7])
len_rel = len_all - offset

inp_ex_expanded = [int(aa) for aa in list(inp_str[offset % len_inp:len_inp])]

inp_ex_expanded = np.hstack([inp_ex_expanded, inp_ex*(len_rel // len_inp)])

In [13]:
start = time.time()
cur = inp_ex_expanded
for ii in range(100):
    next_cur = np.ones(len_rel)*99
    tally = 0
    for jj in range(len_rel-1, -1, -1):
        tally = tally + cur[jj]
        next_cur[jj] = tally
    cur = reduce(next_cur)
end = time.time()
print(end-start)
print(cur[:8])
print('Part two solution:')
print(''.join([str(int(cc)) for cc in cur[:8]]))

27.225311040878296
[2. 3. 7. 5. 2. 5. 7. 9.]
Part two solution:
23752579
